version: '3'
services:
  bpm-registrator:
    build: .
    image: docker.quancy.com.sg/bpm-registrator:${VERSION-latest}
    container_name: bpm-registrator
    network_mode: bridge
    restart: always
    env_file:
      - .env